In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import time
import cobra
from cobra.core import configuration
from PolyRound.api import PolyRoundApi
from PolyRound.settings import PolyRoundSettings
import hopsy

In [3]:
configuration.Configuration.solver = 'glpk'

In [4]:
model = cobra.io.read_sbml_model('./../autopacmen_output/Mitocore_aligned_to_Human1/MitoCore_aligned_to_Human1_calibrated_MA.xml')

In [5]:
model.optimize()

# 1) Sanity check: Model has a solution with lower bound for objective function

In [6]:
# for reaction in model.reactions:
#     if reaction.upper_bound == 0.0 and reaction.lower_bound == 0.0:
#         model.remove_reactions(reaction)

# model.reactions.OF_ATP_MitoCore.lower_bound = 1.707042254 * 0.95
model.optimize()

In [7]:
cobra.io.write_sbml_model(model, './../flux_sampling/chrr_reounding_test_h1_ma.xml')

# 2) Reproduction of the Error

In [10]:
# reinitialize hopsies settings for polyround to use glpk solver
settings = PolyRoundSettings(backend='glpk')
hopsy.LP.settings = settings
hopsy.LP.settings.__dict__

{'backend': 'glpk',
 'hp_flags': {'FeasibilityTol': 1e-09},
 'thresh': 1e-07,
 'verbose': False,
 'sgp': False,
 'reduce': True,
 'regularize': False,
 'check_lps': False,
 'simplify_only': False,
 'presolve': False,
 'numerics_threshold': 1e-12,
 'accepted_tol_violation': 100.0}

In [11]:
polytope = PolyRoundApi.sbml_to_polytope('./../flux_sampling/chrr_reounding_test_h1_ma.xml')
problem = hopsy.Problem(polytope.A, polytope.b) # set the polytype, i.e., the inequality constraints from the constraint based model
problem = hopsy.add_equality_constraints(problem=problem, A_eq=polytope.S, b_eq=polytope.h)
start = time.perf_counter()
problem = hopsy.round(problem)
print(f"Computing rounding transformation for {model_name} took {time.perf_counter()-start} seconds")

1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
0.0
0.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
0.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
0.0
0.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
0.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
0.0
0.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
6e-05
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
0.0
1.188
1000.0
0.1026
0.18594
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1000.0
0.0006
0.00024
0.00096
0.0018
0.0003
0.00072
0.0
0.00048
0.00066
0.00042
1000.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1000.0
1000.0
0.0
1000.0
1000.0
1000.0
1000.0
1000.0
0.0
0.0
0.0
1000.0
0.0
0.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
0.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
0.0
0.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
0.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
0.0
1000.0
0.0
1000.0
0.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
0.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
0.0
0.44508
0.0
0.0006
6e-05
1000.0
0.00054
1000.0
0.00024
1000.0
0.00102
1000.0
0.00066
1000.0
0.0006
1000.0
0.0006
1000.0
1000.0
1000.0
0.63096
0.0006
0.0
1000.0
0.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
0.006
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
0.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
0.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
0.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
0.0
1000.0
0.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
0.0595213740332645
1.65853217793952e-06
1.67518680624112e-06
3.45661519642737e-06
1.22168216821031e-06
1.50479714746318e-06
1.42655699802434e-06
7.46288343871082e-07
7.50914844237064e-07
4.63681558930244e-07
1.42655699802434e-06
7.76911370103061e-07
1.06039309865053e-06
1.37812261980029e-06
1.75189903356972e-06
3.31011615118179e-06
3.6263788741073e-06
1.09984510127666e-06
3.02452593694079e-06
1.84236156579683e-06
2.35879956623265e-06
1.30080952779946e-06
1.06554827393969e-06
1.48124097343858e-06
1.24693873602396e-05
3.02823178136444e-06
2.20737788333324e-06
7.46754684372076e-07
1.58557606281303e-06
7.28852065815524e-06
8.07470186990792e-06
6.1237512123935e-06
2.19738035370662e-06
8.54425905252759e-07
1.7340589807026e-06
1.73643285870508e-06
2.76171707030675e-06
1.94898951546226e-07
1.63953182734191e-06
7.54768620877371e-06
2.50241039148923e-06
1.09505058706862e-06
2.58539031252197e-06
9.87110803711617e-07
2.06521496204842e-06
3.65519850515204e-05
2.96135390798425e-06
4.48311885138951e-06
4.34051428175049e-06
1.03957232200596e-05
4.73653987823806e-06
2.80465326383963e-05
1.05876450111854e-05
1.16552570299384e-06
7.6766668293869e-07
1.94898951546226e-07
5.33528364233212e-07
5.98353227098684e-07
1.80548478060072e-06
7.21817321405561e-05
2.29877095312219e-05
8.23621379732121e-05
2.7008821906088e-06
2.3919287207508e-05
8.78875951952399e-07
1.57186013269648e-06
3.40999097712306e-06
2.17645094919491e-05
6.84363004706448e-05
1.14677500835341e-05
3.68471688430834e-05
2.65974023157706e-05
4.82741141280032e-07
8.267158523265e-07
2.53143063774705e-06
8.91626198527618e-07
2.11333164309867e-06
2.89225579751209e-06
3.7977551270177e-06
3.2826095680886e-05
1.5736878450823e-06
5.1560041212761e-06
3.54273015583303e-06
4.4598406582691e-06
3.27824053474374e-06
1.28978789599136e-06
8.50435904377275e-06
4.32304074758452e-06
1.23663796307941e-06
2.61923918103791e-06
1.22804660396928e-05
3.47566790648284e-06
5.89210306733357e-06
9.31993117626479e-07
1.96505606649697e-05
5.57729723363913e-06
9.55736816425422e-06
3.13386915496184e-05
5.67069233324732e-06
4.96614135863783e-06
4.45319678416898e-05
6.59101337377467e-06
3.48829066566966e-06
6.13041235092255e-07
3.17617728330865e-05
2.51902130685566e-06
1.0085165879158e-06
5.52983891644692e-06
3.35161830201408e-06
5.1560041212761e-06
1.13228064510625e-05
7.79298693569654e-06
9.93363034578877e-06
1.85818705938644e-06
6.09641834902724e-07
2.43463785679421e-06
1.09394975932826e-06
2.26748458844975e-06
4.47792282613942e-06
5.10695195393054e-07
1.41755591888535e-06
4.50022023328607e-05
5.35508759203367e-06
8.58283193944065e-07
8.99227227047406e-06
5.19182316959929e-07
3.48591500547649e-06
1.65017955280346e-06
6.78763723769875e-06
2.27693763864657e-06
5.07609555114215e-06
1.14304019281738e-05
1.98040354050596e-06
9.06279558325592e-06
7.01531613224343e-07
1.33101610542867e-06
2.34201338203624e-06
5.49439151133468e-06
6.47407225676651e-06
1.52230737628964e-06
2.48203616802399e-05
4.74125536794007e-06
1.6113037385681e-05
1.01992337538552e-05
2.21765184235047e-06
2.50447243615541e-06
9.22449189209621e-06
8.30017124454721e-07
5.3434476758133e-07
3.27306763230151e-06
6.29778687007826e-07
3.06865748383727e-06
1.08236636593597e-06
3.73203340148906e-06
2.33066539153992e-06
8.65599949314323e-06
2.03974142502182e-06
1.00785637022504e-06
2.09972466058757e-06
2.55669248991881e-06
3.62249719227468e-06
4.80558627076922e-06
7.0217499771312e-07
2.00210282137987e-06
3.58987727210254e-06
8.18423067670848e-06
7.23085167705362e-06
1.40593318958814e-05
6.1824574579509e-06
7.86645842017862e-07
1.55722001837183e-06
6.62502480881431e-06
2.07952417111892e-06
2.69610336446638e-06
1.31560900117854e-05
8.40941334042654e-07
7.07492767467302e-07
4.63630677828813e-06
3.6939807380911e-06
5.50772099466906e-07
1.59092933326472e-05
1.29341148055823e-06
1.99671217062319e-06
3.20709424194458e-06
5.85560067043124e-07
5.33717087951873e-06
1.31354344883489e-06
1.22780903220841e-06
3.31443907382838e-06
8.07470197118621e-07
3.30772819779228e-06
1.08579095275844e-06
7.61757707637752e-07
7.99807090650335e-07
5.8267149675526e-06
1.07174701801096e-06
5.95201259817569e-06
6.31057497515748e-06
2.97349808773327e-06
6.6692155128754e-06
3.1531165963348e-06
5.07809543732922e-07
6.9235549450006e-06
1.14978041906603e-06
5.97714054196905e-06
1.30105576384158e-06
4.45873880690813e-06
4.57181100546603e-06
8.89266487532719e-06
2.37353259985315e-06
5.62135402970324e-06
1.08656451716299e-05
2.87518521945271e-06
3.44169820981583e-05
9.79023343234124e-07
3.6642252719754e-06
5.28712481370585e-06
3.6710137991622e-06
7.55350584336652e-06
1.59723728492335e-06
1.58055116131239e-06
1.0183243815645e-06
8.45139283585757e-06
5.1560041212761e-06
2.4070724067526e-05
9.34643250722551e-07
6.52226311889989e-07
5.33957309067775e-06
6.33461913889541e-07
2.68203478992893e-06
2.84020398875047e-06
8.09470049532848e-07
1.71883341834187e-06
4.3089732778562e-06
2.81354146534937e-06
3.53184653637311e-06
1.74440760511966e-06
4.27924932565351e-06
4.49575174270318e-07
4.94006441795154e-07
1.73749064890308e-06
8.36529204403356e-07
9.13901332860611e-07
1.06665231060563e-06
1.21080385866266e-06
4.47492908973705e-06
5.3434476758133e-07
2.02528835436843e-06
8.93504421819152e-07
2.03219371034727e-06
7.61965383825384e-07
6.85398373107495e-07
2.97634420054536e-06
1.00785637022504e-06
5.98353227098684e-07
2.54791974865753e-06
9.2960700775293e-07
1.60407715731293e-06
8.25800762859379e-07
4.61883332291208e-07
3.4546970419888e-06
8.92881904629723e-07
3.35558137212008e-06
7.33064764361818e-07
6.45126760663371e-07
8.1555861176481e-07
9.21150182897099e-06
3.47644891332216e-06
1.41577478661757e-06
5.62139690149018e-07
2.60935623450331e-06
3.00073785248207e-06
3.4222273965853e-06
1.08205675870771e-06
4.41293100871418e-06
1.3536903579608e-06
9.78210806446799e-07
9.14389211272159e-07
9.04191440044447e-07
1.64946761246332e-06
2.56577114068472e-06
1.31895727155055e-06
1.85977560325055e-06
1.63964734023252e-06
3.74768143137683e-06
9.38669236889405e-07
1.58789358203962e-06
5.762394001949e-06
1.2251417392467e-06
1.00418587804161e-06
1.66036101706488e-06
7.6431872380206e-07
2.08949214739336e-06
7.40591036665132e-07
2.42790960828432e-06
1.5761894625936e-06
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
1000.0
-0.0
-0.0
-0.0
1000.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
1000.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
1000.0
-0.0
-0.0
-0.0
-0.0
-0.0
1000.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
-0.0
-0.0
-0.0
1000.0
-0.0
2.2986
1000.0
1000.0
1000.0
1000.0
-0.0
-0.0
-0.0
-0.0
-0.0
1000.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
1000.0
0.00924
-0.0
-0.0
-0.0
1000.0
-0.0
-0.0
-0.0
1000.0
1000.0
1000.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
1000.0
1000.0
-0.0
1000.0
1000.0
1000.0
1000.0
1000.0
-0.0
-0.0
-0.0
1000.0
-0.0
-0.0
1000.0
1000.0
1000.0
1000.0
1000.0
1000.0
0.141
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0
-0.0

ValueError: Adding these equality constraints makes the problem infeasible! Check the problem and/or the LP().settings

# 3) Sanity check with MitoMammal model

In [ ]:
polytope = PolyRoundApi.sbml_to_polytope('./../flux_sampling/Mitocore_MitoMammal_sampling_model.xml')
problem = hopsy.Problem(polytope.A, polytope.b) # set the polytype, i.e., the inequality constraints from the constraint based model
problem = hopsy.add_equality_constraints(problem=problem, A_eq=polytope.S, b_eq=polytope.h)
start = time.perf_counter()
problem = hopsy.round(problem)
print(f"Computing rounding transformation for {model_name} took {time.perf_counter()-start} seconds")

GurobiError: Model too large for size-limited license; visit https://gurobi.com/unrestricted for more information

Original model can be rounded, looks like its an issue with ec models

In [ ]:
polytope = PolyRoundApi.sbml_to_polytope('./../flux_sampling/Mitocore_Original_plt_sampling_model.xml')
problem = hopsy.Problem(polytope.A, polytope.b) # set the polytype, i.e., the inequality constraints from the constraint based model
problem = hopsy.add_equality_constraints(problem=problem, A_eq=polytope.S, b_eq=polytope.h)
start = time.perf_counter()
problem = hopsy.round(problem)
print(f"Computing rounding transformation for {model_name} took {time.perf_counter()-start} seconds")

NameError: name 'model_name' is not defined

# 4) Trying to change LP settings

In [ ]:
# reinitialize hopsies settings for polyround to use glpk solver
settings = PolyRoundSettings(backend='glpk', hp_flags = {"FeasibilityTol": 1e-6}, thresh = 1e-12, verbose=True)
hopsy.LP.settings = settings
hopsy.LP.settings.__dict__

{'backend': 'glpk',
 'hp_flags': {'FeasibilityTol': 1e-06},
 'thresh': 1e-12,
 'verbose': True,
 'sgp': False,
 'reduce': True,
 'regularize': False,
 'check_lps': False,
 'simplify_only': False,
 'presolve': False,
 'numerics_threshold': 1e-12,
 'accepted_tol_violation': 100.0}

In [ ]:
polytope = PolyRoundApi.sbml_to_polytope('./../flux_sampling/Mitocore_MitoMammal_sampling_model.xml')
problem = hopsy.Problem(polytope.A, polytope.b) # set the polytype, i.e., the inequality constraints from the constraint based model
problem = hopsy.add_equality_constraints(problem=problem, A_eq=polytope.S, b_eq=polytope.h)
print('1')
start = time.perf_counter()
problem = hopsy.round(problem)
print(f"Computing rounding transformation for {model_name} took {time.perf_counter()-start} seconds")

 Investigating constraint number: 0


 Investigating constraint number: 50


 Investigating constraint number: 100


 Investigating constraint number: 150


 Investigating constraint number: 200


 Investigating constraint number: 250


 Investigating constraint number: 300


 Investigating constraint number: 350


 Investigating constraint number: 400


 Investigating constraint number: 450


 Investigating constraint number: 500


 Investigating constraint number: 550


 Investigating constraint number: 600


 Investigating constraint number: 650


 Investigating constraint number: 700


 Investigating constraint number: 750


 Investigating constraint number: 800


 Investigating constraint number: 850


 Investigating constraint number: 900


 Investigating constraint number: 950


 Investigating constraint number: 1000


 Investigating constraint number: 1050


 Investigating constraint number: 1100


 Investigating constraint number: 1150


 Investigating constraint number: 1200


 Investigating constraint number: 1250


 Investigating constraint number: 1300


 Investigating constraint number: 1350


 Investigating constraint number: 1400


 Investigating constraint number: 1450


 Investigating constraint number: 1500


 Investigating constraint number: 1550

model in infeasible state, resetting lp

 Investigating constraint number: 1600


 Investigating constraint number: 1650


 Investigating constraint number: 1700


 Investigating constraint number: 1750


 Investigating constraint number: 1800


 Investigating constraint number: 1850

model in infeasible state, resetting lp

 Investigating constraint number: 1900


 Investigating constraint number: 1950


 Investigating constraint number: 2000


 Investigating constraint number: 2050


 Investigating constraint number: 2100


 Investigating constraint number: 2150

Number of removed constraints: 1559
Number of refunctioned constraints: 43

 Investigating constraint number: 0


 Investigating constraint number: 50


 Investigating constraint number: 100


 Investigating constraint number: 150


 Investigating constraint number: 200


 Investigating constraint number: 250

model in infeasible state, resetting lp

 Investigating constraint number: 300


 Investigating constraint number: 350

model in infeasible state, resetting lp